version: "3.9"

services:
  llm:
    build: .
    depends_on:
      - elasticsearch
      - qdrant
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTIC_URL=http://elasticsearch:9200
      - QDRANT_URL=http://qdrant:6333
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]  # needs nvidia‑container‑runtime

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: elasticsearch
    mem_limit: 4g  # `-m 4GB`
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # Still give the JVM ~2 GB heap inside the 4 GB container
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
      - "9300:9300"  # extra mapping

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # REST + dashboard
      - "6334:6334"  # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage  # persistent