version: "3.9"

services:
  llm:
    build: .
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTIC_URL=http://elasticsearch:9200
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.6
    container_name: elasticsearch
    mem_limit: 4g
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9200:9200"
      - "9300:9300"
